### ISSUE TITLE
Stage.SampleCLUT returns invalid results

### ISSUE THREAD

**Issue by m-siscogit** [jrshoare/lcmsNET#4]
I am new to LCMS.Net, so I accept the possibility that I may be doing something wrong. I have tried this with several icc profiles, and I can tell by inspecting these profiles with ICC Profile Inspector that the CLUTs exist and are populated with valid data.

I am trying to use Stage.SampleCLUT to retrieve the values stored in the AToB0 LUT of the profile. I have tried with the other LUTs as well, but I've had no luck. According to the lcms2 documentation, if I call SampleCLUT with the StageSamplingFlags.Inspect flag set, the value that's passed back in the output parameter should represent the contents of the LUT. In my callback, the input parameters are being passed back correctly, and I can watch the calls step through the various CMYK steps in the LUT. But the output values appear to be somewhat random. Some of the returned values are NaN, and others are "denormalized" values. Obviously I'm using the float version of the call, but I have tried the version that takes ushorts as well, and I get similar results. Here is a brief snippet of my code:

      GCHandle hNodeLists = GCHandle.Alloc(nodeLists);
      stage.SampleCLUT(_Sampler, (IntPtr)hNodeLists, StageSamplingFlags.Inspect);
      hNodeLists.Free();

My sampler function is called, and the handle is being passed correctly, but the values I'm getting back are unintelligible. Here is a snapshot of the data for a node that should be in gamut, and you can see that the results are not what I would expect.

![LCMS Net SampleCLUT](https://user-images.githubusercontent.com/105870957/206864404-42c7124b-55ce-4aaf-b2cd-4700b05315be.png)

I also understand that this could be a problem in lcms2 itself, but I don't have a good way to test that code. The test bed that is included with the lcms2 distribution doesn't test cmsStageSampleCLutFloat at all.

**Comment by jrshoare** [comment]
I have just pushed a chnage to StageTest.cs that shows how you might use the `Stage.SampleCLUT` method to inspect the contents of the A2B0 tag of the Lab profile embedded in the resources.

This reads the tag to obtain as a `Pipeline` then enumerates each `Stage` and when the CLUT element type is located invokes the `Stage.SampleCLUT` method passing a callback that expects `ushort` parameters.

Little CMS will invoke the callback for each element in the CLUT. Note that the inputs are scaled 0..65535 unlike the selectors in Profile Inspector which show these as 0..15.

```csharp
private static int SamplerInspect16Bit(ushort[] input, ushort[] output, IntPtr cargo)
{
    return 1; // 1 = true, 0 = false
}

[TestMethod()]
public void InspectA2B0UsingStageSampleCLUT()
{
    using (MemoryStream ms = Save(".Resources.Lab.icc"))
    using (var profile = Profile.Open(ms.GetBuffer()))
    using (var pipeline = profile.ReadTag<Pipeline>(TagSignature.AToB0))
    {
        foreach (var stage in pipeline)
        {
            if (stage.StageType == StageSignature.CLutElemType)
            {
                stage.SampleCLUT(SamplerInspect16Bit, IntPtr.Zero, StageSamplingFlags.Inspect);
            }
        }
    }
}
```

**Comment by m-siscogit** [comment]
Thanks for the response, but my issue was not with how to call SampleCLUT. I am calling SampleCLUT already (using the float version), and my callback is getting invoked. My problem is that the data in the output  parameter is invalid (appears to be somewhat random). The values in the input parameters are indeed the CMYK sample points for the CLUT, but the output parameter is filled with garbage.

I just tried this again using the 16 bit sampler, and everything works as expected, with one small exception. The input and output arrays received by the callback have lengths of 9 and 128 respectively. This is not a problem for the input array, because I am pulling the first four elements off the array "manually", but if I try to use Colorimetric.LabEncoded2Float on the output array, it throws an exception because the input array must have a length of 3. So I'm having to create a new ushort[] array to just pull out the first three elements. Reading up a little more on MarshalAs, I see that this is probably a necessary evil, since there's no way to know at compile time how large those arrays must be. This limitation might be a good thing to document in the xml comments for the function.

The double version of the Sampler delegate still seems to be returning garbage, but I've taken a closer look at the lcms2 code, and I don't think the problem is in LCMS.Net. I will try to reach out to the author of lcms2 and see if he has any insight into this problem.

For now I will work with the 16-bit version, and I can at least move forward.

Thanks again. This is an extremely nice piece of work you've done.

**Comment by jrshoare** [comment]
Thanks for the kind words.
